### ISSUE TITLE
Use a changelog generator

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/metapak-nfroidure#3]
Maybe https://www.npmjs.com/package/changelog . See what popular projects use.

**Comment by flexbox** [comment]
Do you know this `git-extras` shortcut ? 
https://github.com/tj/git-extras/blob/master/Commands.md

**Comment by SebastienElet** [comment]
But we could not use `git-extras` as dependency easily as an npm package

**Comment by flexbox** [comment]
Not the hole package maybe it's possible to just embed this file ?
https://github.com/tj/git-extras/blob/master/bin/git-changelog

**Comment by nfroidure** [comment]
There is also https://www.npmjs.com/package/commitizen

**Comment by SebastienElet** [comment]
My company is also working on a way to find all open github issues in the project to propose to close one at commit (with git hook).

**Comment by nfroidure** [comment]
Here is the commit standardization part https://github.com/nfroidure/metapak-nfroidure/commit/5002e26441bf4c6190c035581be1443f21f698e7

I now need to create the changelog based on it.

**Comment by nfroidure** [comment]
https://github.com/nfroidure/metapak-nfroidure/commit/91360a6d012b27e3aa730f711ec20aefd536bfc9
