### ISSUE TITLE
Create a JSDoc config

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/metapak-nfroidure#4]
Generate a doc with `jsdoc2md` and add it to the README.

**Comment by SebastienElet** [comment]
I'm not fan of jsdoc (and {java,php,...}doc), but do you think it's possible to write opinion about coding syntax/style/implementation somewhere in the code ?

For example i would like to comment in my project why we use promises, why we split routes, why we declare routes with metadas etc... I could write few markdowns, but i want to keep the documentation with the code.

**Comment by nfroidure** [comment]
@SebastienElet it matches my current questions too, i have to share our WS stack architecture to Lille's and London's teams and i'll use slides. Would be nice to have something more tied with the code indeed.

And why not, utlimately, generate the slides from it :D https://slides.com/developers#define-api

**Comment by SebastienElet** [comment]
@nfroidure there also files in `coffee.md` like https://github.com/shimaore/esl/tree/master/src :trollface:

**Comment by nfroidure** [comment]
Ahah, the idea itself is good. Won't take that much time to create an AST transformations of JavaScript comment to generate a documentation.

**Comment by nfroidure** [comment]
Note that JSDocs till allows to add examples: https://github.com/nfroidure/knifecycle#constantconstantname-constantvalue--function

**Comment by nfroidure** [comment]
For the AST transformations, what about something like:
```js
/* Architecture note #1 : Application Bootstrap

This is where we bootstrap the application, we use dependency injection with
inversion of control to ensure every services it uses are up and working.

We use [Knifecycle](https://github.com/nfroidure/knifecycle) for that matter.
*/

// Some code (...)


/* Architecture note #1.4 : Shutdown

Here we gracefully shutdown the app.
*/
 
```
Producing ordered markdown that could be appended to the READMEs:

```md
## Architecture notes

### Application Bootstrap

This is where we bootstrap the application, we use dependency injection with
inversion of control to ensure every services it uses are up and working.

We use [Knifecycle](https://github.com/nfroidure/knifecycle) for that matter.

#### Shutdown

Here we gracefully shutdown the app.
```
