### ISSUE TITLE
Can't add authors

### ISSUE THREAD

**Issue by SebastienElet** [nfroidure/metapak-nfroidure#7]
## Issue

I'm a gentledev i:
[x] fully read the README recently
[x] searched for existing issues
[x] checked i'm up to date with the latest version of the project

### Expected behavior

Remove `author` entry to add myself in `authors` array.

### Actual behavior

Metapak re-add the `author` entry at `npm install`.

### Debugging informations
- `node -v` result:
```
6.9.5
```

- `npm -v` result:
```
3.10.10
```
If the result is lower than 6.9.5, there is
 poor chances i even have a look to it. Please,
 use the last [NodeJS LTS version](https://nodejs.org/en/).

**Comment by nfroidure** [comment]
This is normal since it is made for me only ;).
