### ISSUE TITLE
Line endings handling.

### ISSUE THREAD

**Issue by NaridaL** [nfroidure/metapak-nfroidure#8]
How are the line endings supposed to be handled? Currently, if I check out https://github.com/nfroidure/SVGPathData I get windows-style endings in the config files. When I run npm install, it overwrites them with identical files which have linux endings and then Git marks the files as modified.

**Comment by nfroidure** [comment]
@NaridaL thanks for reporting the issue.

That said I cannot reproduce it. I always use Linux line endings on my projects. It may be your editor configuration. Do you have a .editorconfig aware editor? This is the one i use in my projects: https://github.com/nfroidure/metapak-nfroidure/blob/master/.editorconfig

**Comment by NaridaL** [comment]
I read further about the git CRLF handling. I think the issue is the "* text=auto" line in .gitattributes which makes git convert LF to core.eol (in my case CRLF) when writing text files (automatically detected) to the working directory. I could change this setting on my end, but changing the eol setting in the .gitattributes would be more robust.

**Comment by nfroidure** [comment]
I agree, feel free to PR otherwise i'll dive a bit more into that .gitattribute things that, to be hnnest, i just borrowed in another project ;)
